name: Check Formatting

on:
  push:
    branches:
      - master
      - v1
  pull_request:
    branches:
      - master
      - v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check clang-format
      uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '17'
